-- --------------------------------------------------------
-- PostgreSQL Migration Script for Neon DB
-- --------------------------------------------------------

-- 1. Table structure for table "cache"
CREATE TABLE "cache" (
    "key" VARCHAR(255) NOT NULL PRIMARY KEY,
    "value" TEXT NOT NULL,
    "expiration" INTEGER NOT NULL
);

-- Dumping data for table "cache"
INSERT INTO "cache" ("key", "value", "expiration") VALUES
('laravel-cache-spotify_token', 's:139:"BQCnzsuRP7OXq8H2-FBQ83VWqGRV_T3Od2_Ga2VtBjGkQ6ZGvt5t1R-BO24vH56Cr9-OVeRpcT44EZ_f7QwOVo0-g6yaQ-CO3DkbBo4R2IpI2kqd1CQwjA9NC4IaNJBeF7BPm6WPlpk";', 1766455931);


-- --------------------------------------------------------

-- 2. Table structure for table "cache_locks"
CREATE TABLE "cache_locks" (
    "key" VARCHAR(255) NOT NULL PRIMARY KEY,
    "owner" VARCHAR(255) NOT NULL,
    "expiration" INTEGER NOT NULL
);


-- --------------------------------------------------------

-- 3. Table structure for table "migrations"
CREATE TABLE "migrations" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "migration" VARCHAR(255) NOT NULL,
    "batch" INTEGER NOT NULL
);

-- Dumping data for table "migrations"
INSERT INTO "migrations" ("id", "migration", "batch") VALUES
(1, '0001_01_01_000000_create_users_table', 1),
(2, '0001_01_01_000001_create_cache_table', 1),
(3, '0001_01_01_000002_create_jobs_table', 1),
(4, '2025_12_10_174539_create_stories_table', 1),
(5, '2025_12_11_040549_create_story_items_table', 1),
(6, '2025_12_11_041136_add_fields_to_story_items_table', 1);


-- --------------------------------------------------------

-- 4. Table structure for table "password_reset_tokens"
CREATE TABLE "password_reset_tokens" (
    "email" VARCHAR(255) NOT NULL PRIMARY KEY,
    "token" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NULL DEFAULT NULL
);


-- --------------------------------------------------------

-- 5. Table structure for table "users"
-- (Created before sessions/story_items because of Foreign Keys)
CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL UNIQUE,
    "email_verified_at" TIMESTAMP NULL DEFAULT NULL,
    "password" VARCHAR(255) NOT NULL,
    "remember_token" VARCHAR(100) DEFAULT NULL,
    "created_at" TIMESTAMP NULL DEFAULT NULL,
    "updated_at" TIMESTAMP NULL DEFAULT NULL
);

-- Dumping data for table "users"
INSERT INTO "users" ("id", "name", "email", "email_verified_at", "password", "remember_token", "created_at", "updated_at") VALUES
(1, 'Ryan', 'dhantranada70@gmail.com', NULL, '$2y$12$mGzJV8GtfTfemUGTNP7DGegrrluOun51ZnIqqkJyj.BQOJ8ayODeK', NULL, '2025-12-17 18:40:18', '2025-12-17 18:40:18');


-- --------------------------------------------------------

-- 6. Table structure for table "sessions"
CREATE TABLE "sessions" (
    "id" VARCHAR(255) NOT NULL PRIMARY KEY,
    "user_id" BIGINT DEFAULT NULL,
    "ip_address" VARCHAR(45) DEFAULT NULL,
    "user_agent" TEXT DEFAULT NULL,
    "payload" TEXT NOT NULL,
    "last_activity" INTEGER NOT NULL
);

-- Indexes for table "sessions"
CREATE INDEX "sessions_user_id_index" ON "sessions" ("user_id");
CREATE INDEX "sessions_last_activity_index" ON "sessions" ("last_activity");

-- Dumping data for table "sessions"
INSERT INTO "sessions" ("id", "user_id", "ip_address", "user_agent", "payload", "last_activity") VALUES
('1F9EiPXBZ3NqOAQru0FdHDtgTZG5WMmTJv8d9JgM', 1, '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0', 'YTo0OntzOjY6Il90b2tlbiI7czo0MDoiMGE0WmRrU2hpanRJVzM4RjVCUHRtYzcxOVhuaXRqSHNtRkg5YmJEdCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MzE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9kYXNoYm9hcmQiO3M6NToicm91dGUiO3M6OToiZGFzaGJvYXJkIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo1MDoibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiO2k6MTt9', 1766452820),
('X30HkmQP4Y9r9hwcEyN2hM5sTDYAsNiUZnzo477S', 1, '127.0.0.1', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36 Edg/143.0.0.0', 'YTo0OntzOjY6Il90b2tlbiI7czo0MDoiQmtWcFBPMmhZUE1WZ1gyNFZRSEFLelFGUEdVY25sWFZHaVNnQmw0RCI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6NTE6Imh0dHA6Ly8xMjcuMC4wLjE6ODAwMC9hcnRpc3QvQXZyaWwlMjBMYXZpZ25lL2FsYnVtcyI7czo1OiJyb3V0ZSI7czoxMzoiYXJ0aXN0LmFsYnVtcyI7fXM6NjoiX2ZsYXNoIjthOjI6e3M6Mzoib2xkIjthOjA6e31zOjM6Im5ldyI7YTowOnt9fXM6NTA6ImxvZ2luX3dlYl81OWJhMzZhZGRjMmIyZjk0MDE1ODBmMDE0YzdmNThlYTRlMzA5ODlkIjtpOjE7fQ==', 1766198207);


-- --------------------------------------------------------

-- 7. Table structure for table "story_items"
CREATE TABLE "story_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "album_id" VARCHAR(255) DEFAULT NULL,
    "album_name" VARCHAR(255) NOT NULL,
    "artist_name" VARCHAR(255) NOT NULL,
    "album_cover" VARCHAR(255) DEFAULT NULL,
    "favorite" BOOLEAN NOT NULL DEFAULT FALSE, 
    "rating" INTEGER DEFAULT NULL,
    "notes" VARCHAR(1000) DEFAULT NULL,
    "track_count" INTEGER DEFAULT NULL,
    "preview_url" VARCHAR(255) DEFAULT NULL,
    "created_at" TIMESTAMP NULL DEFAULT NULL,
    "updated_at" TIMESTAMP NULL DEFAULT NULL
);

-- Dumping data for table "story_items"
-- Note: '1' translates to TRUE in Postgres boolean logic
INSERT INTO "story_items" ("id", "user_id", "album_id", "album_name", "artist_name", "album_cover", "favorite", "rating", "notes", "track_count", "preview_url", "created_at", "updated_at") VALUES
(15, 1, NULL, 'Let Go', 'Avril Lavigne', 'https://i.scdn.co/image/ab67616d0000b273f7ec724fbf97a30869d06240', TRUE, 5, 'all my life ive been good but now', 13, NULL, '2025-12-19 18:35:05', '2025-12-19 18:35:32');

-- Restart identity sequence to match next ID
ALTER TABLE "story_items" ALTER COLUMN "id" RESTART WITH 16;


-- --------------------------------------------------------
-- Foreign Keys
-- --------------------------------------------------------

ALTER TABLE "story_items"
    ADD CONSTRAINT "story_items_user_id_foreign" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;